version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    env_file:
      - ./env/backend.env
  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    depends_on:
      - backend
    env_file:
      - ./env/frontend.env
