apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fauverick/deranger-backend:latest
          env:
            - name: FRONTEND_URL
              value: "frontend-service.default:8080"
              
